### ISSUE TITLE
error  UNKNOWN RangeError: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by charring** [Microsoft/PowerBI-visuals#143]
I did a clean install - tried on two different computers actually. I get this result:

`C:\dev_samples_experiments\customBiVis\PowerBI-visuals-sampleBarChart-master>pbiviz start
 info   Building visual...
 error  UNKNOWN RangeError: Maximum call stack size exceeded
    at Object.getSpecialPropertyAssignmentKind (C:\Users\chris\AppData\Roaming\npm\node_modules\powerbi-visuals-tools\node_modules\typescript\lib\typescript.js:7688:46)
    at getContextualTypeForBinaryOperand (C:\Users\chris\AppData\Roaming\npm\node_modules\powerbi-visuals-tools\node_modules\typescript\lib\typescript.js:34412:24)
    at getContextualType (C:\Users\chris\AppData\Roaming\npm\node_modules\powerbi-visuals-tools\node_modules\typescript\lib\typescript.js:34592:28)
    at getApparentTypeOfContextualType (C:\Users\chris\AppData\Roaming\npm\node_modules\powerbi-visuals-tools\node_modules\typescript\lib\typescript.js:34544:24)
    at checkObjectLiteral (C:\Users\chris\AppData\Roaming\npm\node_modules\powerbi-visuals-tools\node_modules\typescript\lib\typescript.js:34864:34)
    at checkExpressionWorker (C:\Users\chris\AppData\Roaming\npm\node_modules\powerbi-visuals-tools\node_modules\typescript\lib\typescript.js:38206:28)
    at checkExpression (C:\Users\chris\AppData\Roaming\npm\node_modules\powerbi-visuals-tools\node_modules\typescript\lib\typescript.js:38165:42)
    at getTypeOfExpression (C:\Users\chris\AppData\Roaming\npm\node_modules\powerbi-visuals-tools\node_modules\typescript\lib\typescript.js:38150:20)
    at getAssignedTypeOfBinaryExpression (C:\Users\chris\AppData\Roaming\npm\node_modules\powerbi-visuals-tools\node_modules\typescript\lib\typescript.js:32799:17)
    at getAssignedType (C:\Users\chris\AppData\Roaming\npm\node_modules\powerbi-visuals-tools\node_modules\typescript\lib\typescript.js:32821:28)
`

**Comment by AndrewIverson** [comment]
See the comments about moving .js files from tsconfig.json https://github.com/Microsoft/PowerBI-visuals/issues/136

**Comment by charring** [comment]
Yes, that was the solution
