### ISSUE TITLE
dotplot - TypeError: Cannot read property 'getKey' of null

### ISSUE THREAD

**Issue by LukaszPawlowski-MS** [Microsoft/PowerBI-visuals#160]
After fixing issues with let and const, removing the reference line and fixing .samples namespace. The visual throws an error at:

TypeError: Cannot read property 'getKey' of null
    at Array.<anonymous> (https://msit.powerbi.com/11.0.9168.900/scripts/visuals.min.js:1:5106)
    at e (https://msit.powerbi.com/11.0.9168.900/scripts/powerbi.externals.min.js:363:13173)
    at Array._a.data (https://msit.powerbi.com/11.0.9168.900/scripts/powerbi.externals.min.js:363:13760)
    at c.drawLegendInternal (https://msit.powerbi.com/11.0.9168.900/scripts/visuals.min.js:1:5070)
    at c.drawLegend (https://msit.powerbi.com/11.0.9168.900/scripts/visuals.min.js:1:3730)
    at DotPlot.update (DotPlot1448279543123.js:161:33)
    at n.b.updateVisual (https://msit.powerbi.com/11.0.9168.900/scripts/extensibility.min.js:1:30647)
    at n.b.setVisual (https://msit.powerbi.com/11.0.9168.900/scripts/extensibility.min.js:1:31304)
    at https://msit.powerbi.com/11.0.9168.900/scripts/extensibility.min.js:1:10384
    at n.$broadcast (https://msit.powerbi.com/11.0.9168.900/scripts/angular.min.js:137:360)

**Comment by sgrebnov** [comment]
I saw this issue a few days ago when  using version published to Viz Gallery; we've just published updated one generated from new code that works fine.

@LukaszPawlowski-MS please re-open if can still see this issue.
