### ISSUE TITLE
"Unable to get property 'length' of undefined or null reference" if capabilities does not contain dataViewMappings.

### ISSUE THREAD

**Issue by kiewic** [Microsoft/PowerBI-visuals#285]
In theory `dataViewMappings` is optional in a VisualCapabilities object, as defined in [iVisual.ts][source_code].

However, if the capabilities of a visualization does not contain that property, Power BI Desktop fails with the following errors:

    Error Message:
    
    Unable to get property 'length' of undefined or null reference
    
    Stack Trace:
    
    Microsoft.Mashup.Host.Document.JavaScriptException: Unable to get property 'length' of undefined or null reference
    TypeError: Unable to get property 'length' of undefined or null reference
    at createVisualCapabilitiesHelper (local://pq.microsoft.com/minerva/scripts/explore.js:3631:163)
    at getNumberRangesForRoles (local://pq.microsoft.com/minerva/scripts/explore.js:4346:29)
    at updateBucketCardinality (local://pq.microsoft.com/minerva/scripts/exploreui.js:7988:217)
    at populateBuckets (local://pq.microsoft.com/minerva/scripts/exploreui.js:7965:25)
    at createBuckets (local://pq.microsoft.com/minerva/scripts/exploreui.js:7930:21)
    at FieldWellController.prototype.update (local://pq.microsoft.com/minerva/scripts/exploreui.js:3353:45)
    at Anonymous function (local://pq.microsoft.com/minerva/scripts/exploreui.js:3347:25)
    at Anonymous function (local://pq.microsoft.com/pbi/web/OpenSource/angular/angular.js:109:266)
    at h.prototype.$eval (local://pq.microsoft.com/pbi/web/OpenSource/angular/angular.js:123:128)
    at h.prototype.$digest (local://pq.microsoft.com/pbi/web/OpenSource/angular/angular.js:120:212)
    
    Invocation Stack Trace:
    
    at Microsoft.Mashup.Host.Document.ExceptionExtensions.GetCurrentInvocationStackTrace()
    at Microsoft.Mashup.Client.ClientShared.StackTraceInfo..ctor(String exceptionStackTrace, String invocationStackTrace)
    at Microsoft.Mashup.Client.ClientShared.UnexpectedExceptionHandler.<>c__DisplayClass1.<HandleException>b__0()
    at Microsoft.Mashup.Client.ClientShared.UnexpectedExceptionHandler.HandleException(Exception e)
    at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
    at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
    at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
    at Microsoft.Mashup.Client.ClientShared.JsExportWrapper.<>c__DisplayClass2.<InvokeMember>b__0()
    at Microsoft.Mashup.Client.ClientShared.JsErrorHandler.WrapInvokeHost(Func`1 invokeHost)
    at System.Windows.Forms.UnsafeNativeMethods.DispatchMessageW(MSG& msg)
    at System.Windows.Forms.UnsafeNativeMethods.DispatchMessageW(MSG& msg)
    at System.Windows.Forms.Application.ComponentManager.System.Windows.Forms.UnsafeNativeMethods.IMsoComponentManager.FPushMessageLoop(IntPtr dwComponentID, Int32 reason, Int32 pvLoopData)
    at System.Windows.Forms.Application.ThreadContext.RunMessageLoopInner(Int32 reason, ApplicationContext context)
    at System.Windows.Forms.Application.ThreadContext.RunMessageLoop(Int32 reason, ApplicationContext context)
    at System.Windows.Forms.Form.ShowDialog(IWin32Window owner)
    at Microsoft.Mashup.Client.ClientShared.WindowManager.ShowDialog[T](T form, IWin32Window owner)
    at Microsoft.PowerBI.Client.Program.<>c__DisplayClassa.<Main>b__0()
    at Microsoft.Mashup.Host.Document.ExceptionHandlerExtensions.HandleExceptions(IExceptionHandler exceptionHandler, Action action)
    at Microsoft.PowerBI.Client.Program.Main(String[] args)

And then:

    Error Message:

    [$rootScope:inprog] http://errors.angularjs.org/1.3.0/$rootScope/inprog?p0=%24digest

    Stack Trace:

    Microsoft.Mashup.Host.Document.JavaScriptException: [$rootScope:inprog] http://errors.angularjs.org/1.3.0/$rootScope/inprog?p0=%24digest
    Error: [$rootScope:inprog] http://errors.angularjs.org/1.3.0/$rootScope/inprog?p0=%24digest
       at l (local://pq.microsoft.com/pbi/web/OpenSource/angular/angular.js:115:320)
       at h.prototype.$apply (local://pq.microsoft.com/pbi/web/OpenSource/angular/angular.js:123:330)
       at Anonymous function (local://pq.microsoft.com/pbi/web/OpenSource/angular/angular.js:224:237)
       at n.event.dispatch (local://pq.microsoft.com/opensource/jquery/jquery-2.1.1.js:3:6348)
       at r.handle (local://pq.microsoft.com/opensource/jquery/jquery-2.1.1.js:3:3114)

    Invocation Stack Trace:

       at Microsoft.Mashup.Host.Document.ExceptionExtensions.GetCurrentInvocationStackTrace()
       at Microsoft.Mashup.Client.ClientShared.StackTraceInfo..ctor(String exceptionStackTrace, String invocationStackTrace)
       at Microsoft.Mashup.Client.ClientShared.UnexpectedExceptionHandler.<>c__DisplayClass1.<HandleException>b__0()
       at Microsoft.Mashup.Client.ClientShared.UnexpectedExceptionHandler.HandleException(Exception e)
       at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
       at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
       at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
       at Microsoft.Mashup.Client.ClientShared.JsExportWrapper.<>c__DisplayClass2.<InvokeMember>b__0()
       at Microsoft.Mashup.Client.ClientShared.JsErrorHandler.WrapInvokeHost(Func`1 invokeHost)
       at System.Windows.Forms.UnsafeNativeMethods.DispatchMessageW(MSG& msg)
       at System.Windows.Forms.UnsafeNativeMethods.DispatchMessageW(MSG& msg)
       at System.Windows.Forms.Application.ComponentManager.System.Windows.Forms.UnsafeNativeMethods.IMsoComponentManager.FPushMessageLoop(IntPtr dwComponentID, Int32 reason, Int32 pvLoopData)
       at System.Windows.Forms.Application.ThreadContext.RunMessageLoopInner(Int32 reason, ApplicationContext context)
       at System.Windows.Forms.Application.ThreadContext.RunMessageLoop(Int32 reason, ApplicationContext context)
       at System.Windows.Forms.Form.ShowDialog(IWin32Window owner)
       at Microsoft.Mashup.Client.ClientShared.WindowManager.ShowDialog[T](T form, IWin32Window owner)
       at Microsoft.PowerBI.Client.Program.<>c__DisplayClassa.<Main>b__0()
       at Microsoft.Mashup.Host.Document.ExceptionHandlerExtensions.HandleExceptions(IExceptionHandler exceptionHandler, Action action)
       at Microsoft.PowerBI.Client.Program.Main(String[] args)

[source_code]: https://github.com/Microsoft/PowerBI-visuals/blob/14498d3899f17eac1ca7454d95385aa1fb7ba750/src/Clients/Visuals/iVisual.ts#L167

**Comment by ignatvilesov** [comment]
@kiewic As I know, this problem was fixed.
Let us know if you have this problem again.
