### ISSUE TITLE
Unable to build playground project: TypeError: Object [object Object] has no method 'parse'

### ISSUE THREAD

**Issue by mmartsen** [Microsoft/PowerBI-visuals#449]
Hi guys,
Im trying to follow instructions for current version of repo and getting the build error:
`> cmd.exe /c gulp -b "C:\Work\PowerBI-visuals" --color --gulpfile "C:\Work\PowerBI-visuals\Gulpfile.js" build
[21:31:42] Using gulpfile C:\Work\PowerBI-visuals\Gulpfile.js
[21:31:42] Starting 'build:copy-externals'...
[21:31:42] Finished 'build:copy-externals' after 95 ms
[21:31:42] Starting 'build'...
Process terminated with code 1.
[21:31:47] 'build' errored after 5.4 s
[21:31:47] TypeError: Object [object Object] has no method 'parse'
    at extractFormatFromCSSFilename (C:\Work\PowerBI-visuals\node_modules\webpack-spritesmith\lib\processOptions.js:52:38)
    at module.exports (C:\Work\PowerBI-visuals\node_modules\webpack-spritesmith\lib\processOptions.js:23:21)
    at Object.SpritesmithPlugin (C:\Work\PowerBI-visuals\node_modules\webpack-spritesmith\lib\Plugin.js:8:20)
    at Object.<anonymous> (C:\Work\PowerBI-visuals\webpack.config.js:163:9)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at getWebPackConfig (C:\Work\PowerBI-visuals\Gulpfile.js:119:25)
    at runBuild (C:\Work\PowerBI-visuals\Gulpfile.js:201:13)
    at Gulp.<anonymous> (C:\Work\PowerBI-visuals\Gulpfile.js:187:12)
    at module.exports (C:\Work\PowerBI-visuals\node_modules\gulp\node_modules\orchestrator\lib\runTask.js:34:7)
    at Gulp.Orchestrator._runTask (C:\Work\PowerBI-visuals\node_modules\gulp\node_modules\orchestrator\index.js:273:3)
    at Gulp.Orchestrator._runStep (C:\Work\PowerBI-visuals\node_modules\gulp\node_modules\orchestrator\index.js:214:10)
`

$ node --version
v4.4.5

Can you please suggest what can be the issue?

**Comment by ignatvilesov** [comment]
@mmartsen As I see, you used Visual Studio 2015 to compile Power BI, but VS 2015 contains the old version of node.js.

To compile Power BI visuals via Visual Studio 2015, you should execute the following steps:

1. Install node.js (4.x or 5.x).
2. Open Visual Studio 2015.
3. Go to Tools -> Options, then Projects and Solutions -> External Web Tools.
4. Move $(PATH) to the first position.

**Comment by mmartsen** [comment]
@ignatvilesov yes, it works now. Thanks so much!
