### ISSUE TITLE
Issues running gulp build

### ISSUE THREAD

**Issue by chriskabat** [Microsoft/PowerBI-visuals#467]
I believe I followed all of the instructions.  When I run gulp build, I get the below error.   I had installed 6.x, but completely reinstalled and am running 4.4.7.

[21:00:24] Webpack build: finished
[21:00:24] [webpack]
 
ERROR in ./src/Clients/PowerBIVisualsTests/testsInfra.ts
Module build failed: TypeError: Path must be a string. Received undefined
    at assertPath (path.js:7:11)
    at Object.dirname (path.js:697:5)
    at ensureTypeScriptInstance (C:\src\PowerBI-visuals\node_modules\ts-loader\index.js:154:103)
    at Object.loader (C:\src\PowerBI-visuals\node_modules\ts-loader\index.js:387:14)

**Comment by chriskabat** [comment]
This was resolved by uninstalling node.js and installing 5.12.0.

**Comment by dmitriy-tarasov** [comment]
I've checked build under the node 4.4.7 and it seems to work fine. As for the node 6.x versions - it doesn't work for now because of webpack issue: https://github.com/webpack/webpack/issues/2463
