### ISSUE TITLE
are samples available built against 2.1?

### ISSUE THREAD

**Issue by rdegrove** [microsoft/PowerBI-visuals#498]
Says 2.1 at the top of the samplers page but when I download samples they all reference ".api/v1.13.0/PowerBI-visuals.d.ts"... and that isn't even included in the download.

**Comment by uve** [comment]
@rdegrove if you want to use API 2.1 for your samples just run the following command:
`pbiviz update 2.1`

**Comment by rdegrove** [comment]
Thanks.  Since the samples don’t include the api folder, I just copied it from my generated project.  Would the update do anything more than that that I missed?

Russell H. deGrove | Senior Solutions Architect
850-684-9148 | russell.degrove@cloudnav.com
[cid:image001.png@01D4183F.A3A801D0]<http://cloudnav.com/>

[msft allcomps logo mid]

**Comment by rdegrove** [comment]
*   @rdegrove<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Frdegrove&data=02%7C01%7Crussell.degrove%40cloudnav.com%7C4f1893df574248d7d90b08d62aebf888%7C2c7f719da7304a44b8190fd5531f62c8%7C0%7C0%7C636743590332145487&sdata=hp2n7FmTX7KxyX0prhLnrXvk0w8jKsvIavZlNif9rIA%3D&reserved=0> if you want to use API 2.1 for your samples just run the following command:
pbiviz update 2.1

Does not work from a 1.5 visual


PS C:\Users\russell\Source\Workspaces\FloridaHealthFinder\PBI\fHFFilter> pbiviz update 2.1.0

error  UPDATE ERROR { Error: ENOENT: no such file or directory, open 'C:\Users\russell\Source\Workspaces\FloridaHealthF
inder\PBI\fHFFilter\.vscode\settings.json'
    at Object.openSync (fs.js:436:3)
    at Object.readFileSync (fs.js:341:35)
    at Object.readFileSync (C:\Users\russell\AppData\Roaming\npm\node_modules\powerbi-visuals-tools\node_modules\jsonfil
e\index.js:66:20)
    at Function.setApiVersion (C:\Users\russell\AppData\Roaming\npm\node_modules\powerbi-visuals-tools\lib\VisualGenerat
or.js:336:33)
    at VisualGenerator.updateApi.then (C:\Users\russell\AppData\Roaming\npm\node_modules\powerbi-visuals-tools\bin\pbivi
z-update.js:54:94)
    at process._tickCallback (internal/process/next_tick.js:68:7)
    at Function.Module.runMain (internal/modules/cjs/loader.js:745:11)
    at startup (internal/bootstrap/node.js:279:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:752:3)
  errno: -4058,
  syscall: 'open',
  code: 'ENOENT',
  path:


Russell H. deGrove | Senior Solutions Architect
850-684-9148 | russell.degrove@cloudnav.com
[cid:image001.png@01D4183F.A3A801D0]<http://cloudnav.com/>

[msft allcomps logo mid]
