### ISSUE TITLE
Date picker not binding

### ISSUE THREAD

**Issue by DNorthcott** [microsoft/PowerBI-visuals#546]
Hi there,

I have implemented a date picker in the formatting tools.  

![image](https://user-images.githubusercontent.com/34477989/58076655-24b84600-7bee-11e9-8ea5-e6d2a713fd4b.png)

The default date value does not get populated.  This is the enumerateObjectInstances method:

        case "enddate":
          properties.push({
            objectName: objectName,
            displayName: "End Date",
            properties: {
              endDate: this.settings.enddate.value
            },
            selector: null
          });
          break;

Further I am able to select dates in Power BI online fine.  However on desktop I get the error:

Error Message:
An error occurred while rendering the report.

Stack Trace:
TypeError: _this.ngModel.$viewValue.toLocaleDateString is not a function
    at Object.ngModel.$render (ms-pbi://pbi.microsoft.com/minerva/scripts/exploreui.js:7140:66)
    at Object.$processModelValue (ms-pbi://pbi.microsoft.com/minerva/scripts/angular.js:29574:12)
    at Object.$$setModelValue (ms-pbi://pbi.microsoft.com/minerva/scripts/angular.js:29601:10)
    at ngModelWatch (ms-pbi://pbi.microsoft.com/minerva/scripts/angular.js:29640:12)
    at Scope.$digest (ms-pbi://pbi.microsoft.com/minerva/scripts/angular.js:18386:34)
    at ms-pbi://pbi.microsoft.com/minerva/scripts/desktop.js:26040:87
    at ZoneDelegate.invoke (ms-pbi://pbi.microsoft.com/minerva/scripts/desktop.js:49338:176)
    at Object.onInvoke (ms-pbi://pbi.microsoft.com/minerva/scripts/desktop.js:1969:60)
    at ZoneDelegate.invoke (ms-pbi://pbi.microsoft.com/minerva/scripts/desktop.js:49338:64)
    at Zone.run (ms-pbi://pbi.microsoft.com/minerva/scripts/desktop.js:49202:55)

Stack Trace Message:
An error occurred while rendering the report.

JS Error Message:
_this.ngModel.$viewValue.toLocaleDateString is not a function

**Comment by helen508light** [comment]
may be you need to check or make force transform to Date type, because due to error viewValue is not Date type (may be string or timestamp)
