### ISSUE TITLE
custom visual stays blank after 'PBIVIZ start' (gantt chart)

### ISSUE THREAD

**Issue by qingcheng52** [microsoft/PowerBI-visuals#551]
Hi all, 

I am trying to clone the gantt chart from github, after I **clone** it to my VS Code, I ran the **'npm install'** and also installed the d3@3.5.5. when I try the **'pbiviz start'**, everything seems fine but the visual stays blank even I put data in.

I am very new to the custom visual and wonder which step I did was wrong. Pls let me know if you have the options on it.

Can't thank you more!

![image](https://user-images.githubusercontent.com/23001491/58905395-7ff23a00-86be-11e9-80b2-6b989b386080.png)
![image](https://user-images.githubusercontent.com/23001491/58905444-9ac4ae80-86be-11e9-88ba-007fab1c61d9.png)

**Comment by zBritva** [comment]
Hello @qingcheng52, 

Try to open https://localhost:8080/assets/status 

You can see that browser blocked request because certificate isn't trusted. You need to click to "Advanced" and "Proceed" to resolve. After that Power BI can load the visual code.

**Comment by qingcheng52** [comment]
> Hello @qingcheng52,
> 
> Try to open https://localhost:8080/assets/status
> 
> You can see that browser blocked request because certificate isn't trusted. You need to click to "Advanced" and "Proceed" to resolve. After that Power BI can load the visual code.

Hi zBritva,
Thanks for the kind reply. I did use your solution before, it helps when my visual showed "can't contact visual server". But this time even I opened the link for certificate, the visual stays blank.
The interesting part is, I can clone other visuals like [forcegraph](https://github.com/Microsoft/powerbi-visuals-forcegraph/) to local successfully, using the same steps. I followed the following steps:

**git:clone https://github.com/microsoft/powerbi-visuals-gantt.git in VS Code(use Gantt as example)

npm install

pbiviz start** 

The only wired thing I faced when cloning gantt chart, is that I deleted a line in pbiviz.json because of a missing file called "dependencies,json", I am not sure if I should do that or not but it caused error when runing "pbiviz start". Please see below:
![Capture](https://user-images.githubusercontent.com/23001491/59079970-2bf07c80-889b-11e9-9167-444128714610.PNG)
![Capture1](https://user-images.githubusercontent.com/23001491/59079975-30b53080-889b-11e9-97f5-3448dc9b8c1d.PNG)


Please let me know if any of my steps is wrong or I shouldn't delete the line. Thanks so so so much for that!

**Comment by zBritva** [comment]
It's old project. You need to remove "dependencies" to resolve error. It's for R-visuals only. The new tools gives error if you forget to create dependencies.json file.

Or you can consider to use another branch:
https://github.com/microsoft/powerbi-visuals-gantt/tree/dev/next
In this branch the visual converted to use by new tools.

You can get blank visual in case on some error in the visual at runtime. Could you share browser console output?

**Comment by qingcheng52** [comment]
> It's old project. You need to remove "dependencies" to resolve error. It's for R-visuals only. The new tools gives error if you forget to create dependencies.json file.
> 
> Or you can consider to use another branch:
> https://github.com/microsoft/powerbi-visuals-gantt/tree/dev/next
> In this branch the visual converted to use by new tools.
> 
> You can get blank visual in case on some error in the visual at runtime. Could you share browser console output?

Hi zBritva,
Many thanks for the reply! I tried the new branch too, the visual is still blank:(
I attached the browser console as below, I can see there are some warnings, but I have no clue how to fix them.
 
![image](https://user-images.githubusercontent.com/23001491/59120148-7f011880-8909-11e9-8326-348ce585d9c4.png)

**Comment by qingcheng52** [comment]
The more detailed description is as below:

ai.0.js:1 AI: StringValueTooLong message:"string value is too long. It has been truncated to 1024 characters." props:"{value:TypeError: Cannot read property 'resolve' of undefined\n    at i.enumerateObjectRepetitionAsync (https://app.powerbi.com/13.0.9624.223/scripts/powerbiportal.common.bundle.min.js:40:17358)\n    at r.enumerateObjectRepetitionAsync (https://app.powerbi.com/13.0.9624.223/scripts/powerbiportal.common.bundle.min.js:37:4286)\n    at https://app.powerbi.com/13.0.9624.223/scripts/powerbiportal.common.bundle.min.js:37:8369\n    at t.invoke (https://app.powerbi.com/13.0.9624.223/scripts/powerbiportal.dependencies.externals.bundle.min.js:6:28366)\n    at r.run (https://app.powerbi.com/13.0.9624.223/scripts/powerbiportal.dependencies.externals.bundle.min.js:6:23516)\n    at e.runOutsideAngular (https://app.powerbi.com/13.0.9624.223/scripts/web.bundle.min.js:6:165970)\n    at e.executeOutsideAngularZone (https://app.powerbi.com/13.0.9624.223/scripts/powerbiportal.common.bundle.min.js:37:8330)\n    at e.enumerateObjectRepetitionAsync (https://app.powerbi.com/13.0.9624.223/scripts/powerbiportal.common.bundle.min.js:37:7896)\n    at h}"
o.warnToConsole @ ai.0.js:1
o.throwInternal @ ai.0.js:1
t.sanitizeString @ ai.0.js:1
t.sanitizeProperties @ ai.0.js:1
n @ ai.0.js:1
n.trackEvent @ ai.0.js:1
e.trackEventInternal @ web.bundle.min.js:6
e.endTimedEvent @ web.bundle.min.js:6
e.logEvent @ web.bundle.min.js:6
e.logEvent @ web.bundle.min.js:6
e.logEventInternal @ web.bundle.min.js:6
e.logEvent @ web.bundle.min.js:6
t.executeSafely @ powerbiportal.common.bundle.min.js:37
t.enumerateObjectRepetitionAsync @ powerbiportal.common.bundle.min.js:37
r @ powerbiportal.explore.bundle.min.js:7
e.createBuckets @ exploreUIShell.min.js:9
(anonymous) @ exploreUIShell.min.js:5
r @ powerbiportal.common.bundle.min.js:15
(anonymous) @ powerbiportal.common.bundle.min.js:15
a @ powerbiportal.common.bundle.min.js:15
(anonymous) @ powerbiportal.dependencies.externals.bundle.min.js:147
$digest @ powerbiportal.dependencies.externals.bundle.min.js:158
$apply @ powerbiportal.dependencies.externals.bundle.min.js:161
(anonymous) @ powerbiportal.dependencies.externals.bundle.min.js:298
dispatch @ powerbiportal.dependencies.externals.bundle.min.js:9
r.handle @ powerbiportal.dependencies.externals.bundle.min.js:9
t.invokeTask @ powerbiportal.dependencies.externals.bundle.min.js:6
onInvokeTask @ web.bundle.min.js:6
t.invokeTask @ powerbiportal.dependencies.externals.bundle.min.js:6
r.runTask @ powerbiportal.dependencies.externals.bundle.min.js:6
e.invokeTask @ powerbiportal.dependencies.externals.bundle.min.js:6
h @ powerbiportal.dependencies.externals.bundle.min.js:6
d @ powerbiportal.dependencies.externals.bundle.min.js:6
Show 3 more frames
VM2437:19573 [Deprecation] 'window.webkitStorageInfo' is deprecated. Please use 'navigator.webkitTemporaryStorage' or 'navigator.webkitPersistentStorage' instead.
(anonymous) @ VM2437:19573
(anonymous) @ VM2437:19628
i @ visualhostcore.min.js:2
r @ visualsandbox.min.js:1
i.loadWithoutResourcePackage @ visualsandbox.min.js:1
i.executeMessage @ visualsandbox.min.js:1
i.onMessageReceived @ visualsandbox.min.js:1
(anonymous) @ visualsandbox.min.js:1
e.invokeHandler @ visualhostcore.min.js:3
e.dispatchMessage @ visualhostcore.min.js:3
e.onMessageReceived @ visualhostcore.min.js:3
windowMessageHandler @ visualhostcore.min.js:3
dispatch @ visualsandbox.minimal.externals.js:21846
elemData.handle @ visualsandbox.minimal.externals.js:21658
postMessage (async)
e.flushQueue @ powerbiportal.common.bundle.min.js:36
i.ready @ powerbiportal.common.bundle.min.js:39
o.onIFrameLoad @ powerbiportal.common.bundle.min.js:40
(anonymous) @ powerbiportal.common.bundle.min.js:40
e @ powerbiportal.dependencies.externals.bundle.min.js:9
dispatch @ powerbiportal.dependencies.externals.bundle.min.js:9
r.handle @ powerbiportal.dependencies.externals.bundle.min.js:9
t.invokeTask @ powerbiportal.dependencies.externals.bundle.min.js:6
onInvokeTask @ web.bundle.min.js:6
t.invokeTask @ powerbiportal.dependencies.externals.bundle.min.js:6
r.runTask @ powerbiportal.dependencies.externals.bundle.min.js:6
e.invokeTask @ powerbiportal.dependencies.externals.bundle.min.js:6
h @ powerbiportal.dependencies.externals.bundle.min.js:6
d @ powerbiportal.dependencies.externals.bundle.min.js:6
load (async)
E @ powerbiportal.dependencies.externals.bundle.min.js:6
t.scheduleTask @ powerbiportal.dependencies.externals.bundle.min.js:6
onScheduleTask @ powerbiportal.dependencies.externals.bundle.min.js:6
t.scheduleTask @ powerbiportal.dependencies.externals.bundle.min.js:6
r.scheduleTask @ powerbiportal.dependencies.externals.bundle.min.js:6
r.scheduleEventTask @ powerbiportal.dependencies.externals.bundle.min.js:6
(anonymous) @ powerbiportal.dependencies.externals.bundle.min.js:6
add @ powerbiportal.dependencies.externals.bundle.min.js:9
(anonymous) @ powerbiportal.dependencies.externals.bundle.min.js:9
each @ powerbiportal.dependencies.externals.bundle.min.js:8
each @ powerbiportal.dependencies.externals.bundle.min.js:8
ja @ powerbiportal.dependencies.externals.bundle.min.js:9
one @ powerbiportal.dependencies.externals.bundle.min.js:9
o.initContainer @ powerbiportal.common.bundle.min.js:40
(anonymous) @ powerbiportal.common.bundle.min.js:40
t.invokeTask @ powerbiportal.dependencies.externals.bundle.min.js:6
onInvokeTask @ web.bundle.min.js:6
t.invokeTask @ powerbiportal.dependencies.externals.bundle.min.js:6
r.runTask @ powerbiportal.dependencies.externals.bundle.min.js:6
e.invokeTask @ powerbiportal.dependencies.externals.bundle.min.js:6
i.useG.invoke @ powerbiportal.dependencies.externals.bundle.min.js:6
n @ powerbiportal.dependencies.externals.bundle.min.js:6
setTimeout (async)
i @ powerbiportal.dependencies.externals.bundle.min.js:6
t.scheduleTask @ powerbiportal.dependencies.externals.bundle.min.js:6
onScheduleTask @ powerbiportal.dependencies.externals.bundle.min.js:6
t.scheduleTask @ powerbiportal.dependencies.externals.bundle.min.js:6
r.scheduleTask @ powerbiportal.dependencies.externals.bundle.min.js:6
r.scheduleMacroTask @ powerbiportal.dependencies.externals.bundle.min.js:6
n @ powerbiportal.dependencies.externals.bundle.min.js:6
(anonymous) @ powerbiportal.dependencies.externals.bundle.min.js:6
r.<computed> @ powerbiportal.dependencies.externals.bundle.min.js:6
o.init @ powerbiportal.common.bundle.min.js:40
(anonymous) @ powerbiportal.common.bundle.min.js:40
(anonymous) @ powerbiportal.dependencies.externals.bundle.min.js:147
$digest @ powerbiportal.dependencies.externals.bundle.min.js:158
(anonymous) @ powerbiportal.dependencies.externals.bundle.min.js:161
e @ powerbiportal.dependencies.externals.bundle.min.js:58
(anonymous) @ powerbiportal.dependencies.externals.bundle.min.js:61
t.invokeTask @ powerbiportal.dependencies.externals.bundle.min.js:6
onInvokeTask @ web.bundle.min.js:6
t.invokeTask @ powerbiportal.dependencies.externals.bundle.min.js:6
r.runTask @ powerbiportal.dependencies.externals.bundle.min.js:6
e.invokeTask @ powerbiportal.dependencies.externals.bundle.min.js:6
i.useG.invoke @ powerbiportal.dependencies.externals.bundle.min.js:6
n @ powerbiportal.dependencies.externals.bundle.min.js:6
setTimeout (async)
i @ powerbiportal.dependencies.externals.bundle.min.js:6
t.scheduleTask @ powerbiportal.dependencies.externals.bundle.min.js:6
onScheduleTask @ powerbiportal.dependencies.externals.bundle.min.js:6
t.scheduleTask @ powerbiportal.dependencies.externals.bundle.min.js:6
r.scheduleTask @ powerbiportal.dependencies.externals.bundle.min.js:6
r.scheduleMacroTask @ powerbiportal.dependencies.externals.bundle.min.js:6
n @ powerbiportal.dependencies.externals.bundle.min.js:6
(anonymous) @ powerbiportal.dependencies.externals.bundle.min.js:6
r.<computed> @ powerbiportal.dependencies.externals.bundle.min.js:6
k.defer @ powerbiportal.dependencies.externals.bundle.min.js:61
$evalAsync @ powerbiportal.dependencies.externals.bundle.min.js:161
(anonymous) @ powerbiportal.dependencies.externals.bundle.min.js:145
h @ powerbiportal.dependencies.externals.bundle.min.js:147
then @ powerbiportal.dependencies.externals.bundle.min.js:149
r.getSchemaAndExecuteAction @ powerbiportal.explore.bundle.min.js:43
r.registerUndoableAction @ powerbiportal.explore.bundle.min.js:43
r.convert @ powerbiportal.explore.bundle.min.js:42
t.onVisualConversion @ powerbiportal.explore.bundle.min.js:38
(anonymous) @ powerbiportal.explore.bundle.min.js:38
$emit @ powerbiportal.dependencies.externals.bundle.min.js:162
i.publishBubbling @ powerbiportal.explore.bundle.min.js:35
i.convertTo @ powerbiportal.explore.bundle.min.js:34
i.visualCapabilitiesChanged @ powerbiportal.explore.bundle.min.js:34
visualCapabilitiesChanged @ powerbiportal.explore.bundle.min.js:34
t.invoke @ powerbiportal.dependencies.externals.bundle.min.js:6
onInvoke @ web.bundle.min.js:6
t.invoke @ powerbiportal.dependencies.externals.bundle.min.js:6
r.run @ powerbiportal.dependencies.externals.bundle.min.js:6
e.run @ web.bundle.min.js:6
i @ powerbiportal.explore.bundle.min.js:49
visualCapabilitiesChanged @ powerbiportal.explore.bundle.min.js:49
i.setCapabilities @ powerbiportal.common.bundle.min.js:40
(anonymous) @ powerbiportal.common.bundle.min.js:40
i @ powerbiportal.dependencies.externals.bundle.min.js:8
fireWith @ powerbiportal.dependencies.externals.bundle.min.js:8
z @ powerbiportal.dependencies.externals.bundle.min.js:10
(anonymous) @ powerbiportal.dependencies.externals.bundle.min.js:10
tt @ powerbiportal.dependencies.externals.bundle.min.js:7
t.invokeTask @ powerbiportal.dependencies.externals.bundle.min.js:6
r.runTask @ powerbiportal.dependencies.externals.bundle.min.js:6
e.invokeTask @ powerbiportal.dependencies.externals.bundle.min.js:6
h @ powerbiportal.dependencies.externals.bundle.min.js:6
d @ powerbiportal.dependencies.externals.bundle.min.js:6
load (async)
E @ powerbiportal.dependencies.externals.bundle.min.js:6
t.scheduleTask @ powerbiportal.dependencies.externals.bundle.min.js:6
r.scheduleTask @ powerbiportal.dependencies.externals.bundle.min.js:6
r.scheduleEventTask @ powerbiportal.dependencies.externals.bundle.min.js:6
(anonymous) @ powerbiportal.dependencies.externals.bundle.min.js:6
r.set @ powerbiportal.dependencies.externals.bundle.min.js:6
send @ powerbiportal.dependencies.externals.bundle.min.js:10
ajax @ powerbiportal.dependencies.externals.bundle.min.js:10
n.each.n.<computed> @ powerbiportal.dependencies.externals.bundle.min.js:10
(anonymous) @ powerbiportal.common.bundle.min.js:40
i @ powerbiportal.dependencies.externals.bundle.min.js:8
fireWith @ powerbiportal.dependencies.externals.bundle.min.js:8
z @ powerbiportal.dependencies.externals.bundle.min.js:10
(anonymous) @ powerbiportal.dependencies.externals.bundle.min.js:10
tt @ powerbiportal.dependencies.externals.bundle.min.js:7
t.invokeTask @ powerbiportal.dependencies.externals.bundle.min.js:6
r.runTask @ powerbiportal.dependencies.externals.bundle.min.js:6
e.invokeTask @ powerbiportal.dependencies.externals.bundle.min.js:6
h @ powerbiportal.dependencies.externals.bundle.min.js:6
d @ powerbiportal.dependencies.externals.bundle.min.js:6
load (async)
E @ powerbiportal.dependencies.externals.bundle.min.js:6
t.scheduleTask @ powerbiportal.dependencies.externals.bundle.min.js:6
r.scheduleTask @ powerbiportal.dependencies.externals.bundle.min.js:6
r.scheduleEventTask @ powerbiportal.dependencies.externals.bundle.min.js:6
(anonymous) @ powerbiportal.dependencies.externals.bundle.min.js:6
r.set @ powerbiportal.dependencies.externals.bundle.min.js:6
send @ powerbiportal.dependencies.externals.bundle.min.js:10
ajax @ powerbiportal.dependencies.externals.bundle.min.js:10
(anonymous) @ powerbiportal.common.bundle.min.js:40
i @ powerbiportal.dependencies.externals.bundle.min.js:8
fireWith @ powerbiportal.dependencies.externals.bundle.min.js:8
z @ powerbiportal.dependencies.externals.bundle.min.js:10
(anonymous) @ powerbiportal.dependencies.externals.bundle.min.js:10
tt @ powerbiportal.dependencies.externals.bundle.min.js:7
t.invokeTask @ powerbiportal.dependencies.externals.bundle.min.js:6
r.runTask @ powerbiportal.dependencies.externals.bundle.min.js:6
e.invokeTask @ powerbiportal.dependencies.externals.bundle.min.js:6
h @ powerbiportal.dependencies.externals.bundle.min.js:6
d @ powerbiportal.dependencies.externals.bundle.min.js:6
load (async)
E @ powerbiportal.dependencies.externals.bundle.min.js:6
t.scheduleTask @ powerbiportal.dependencies.externals.bundle.min.js:6
r.scheduleTask @ powerbiportal.dependencies.externals.bundle.min.js:6
r.scheduleEventTask @ powerbiportal.dependencies.externals.bundle.min.js:6
(anonymous) @ powerbiportal.dependencies.externals.bundle.min.js:6
r.set @ powerbiportal.dependencies.externals.bundle.min.js:6
send @ powerbiportal.dependencies.externals.bundle.min.js:10
ajax @ powerbiportal.dependencies.externals.bundle.min.js:10
n.each.n.<computed> @ powerbiportal.dependencies.externals.bundle.min.js:10
getJSON @ powerbiportal.dependencies.externals.bundle.min.js:10
(anonymous) @ powerbiportal.common.bundle.min.js:40
i @ powerbiportal.dependencies.externals.bundle.min.js:8
fireWith @ powerbiportal.dependencies.externals.bundle.min.js:8
z @ powerbiportal.dependencies.externals.bundle.min.js:10
(anonymous) @ powerbiportal.dependencies.externals.bundle.min.js:10
tt @ powerbiportal.dependencies.externals.bundle.min.js:7
t.invokeTask @ powerbiportal.dependencies.externals.bundle.min.js:6
r.runTask @ powerbiportal.dependencies.externals.bundle.min.js:6
e.invokeTask @ powerbiportal.dependencies.externals.bundle.min.js:6
h @ powerbiportal.dependencies.externals.bundle.min.js:6
d @ powerbiportal.dependencies.externals.bundle.min.js:6
load (async)
E @ powerbiportal.dependencies.externals.bundle.min.js:6
t.scheduleTask @ powerbiportal.dependencies.externals.bundle.min.js:6
r.scheduleTask @ powerbiportal.dependencies.externals.bundle.min.js:6
r.scheduleEventTask @ powerbiportal.dependencies.externals.bundle.min.js:6
(anonymous) @ powerbiportal.dependencies.externals.bundle.min.js:6
r.set @ powerbiportal.dependencies.externals.bundle.min.js:6
send @ powerbiportal.dependencies.externals.bundle.min.js:10
ajax @ powerbiportal.dependencies.externals.bundle.min.js:10
n.each.n.<computed> @ powerbiportal.dependencies.externals.bundle.min.js:10
i.reloadAdapter @ powerbiportal.common.bundle.min.js:40
i.init @ powerbiportal.common.bundle.min.js:40
r.init @ powerbiportal.common.bundle.min.js:37
(anonymous) @ powerbiportal.common.bundle.min.js:37
t.invoke @ powerbiportal.dependencies.externals.bundle.min.js:6
r.run @ powerbiportal.dependencies.externals.bundle.min.js:6
e.runOutsideAngular @ web.bundle.min.js:6
e.executeOutsideAngularZone @ powerbiportal.common.bundle.min.js:37
e.init @ powerbiportal.common.bundle.min.js:37
(anonymous) @ powerbiportal.common.bundle.min.js:37
t.executeSafely @ powerbiportal.common.bundle.min.js:37
t.init @ powerbiportal.common.bundle.min.js:37
(anonymous) @ powerbiportal.common.bundle.min.js:39
(anonymous) @ powerbiportal.dependencies.externals.bundle.min.js:147
$digest @ powerbiportal.dependencies.externals.bundle.min.js:158
$apply @ powerbiportal.dependencies.externals.bundle.min.js:161
(anonymous) @ powerbiportal.dependencies.externals.bundle.min.js:298
dispatch @ powerbiportal.dependencies.externals.bundle.min.js:9
r.handle @ powerbiportal.dependencies.externals.bundle.min.js:9
t.invokeTask @ powerbiportal.dependencies.externals.bundle.min.js:6
onInvokeTask @ web.bundle.min.js:6
t.invokeTask @ powerbiportal.dependencies.externals.bundle.min.js:6
r.runTask @ powerbiportal.dependencies.externals.bundle.min.js:6
e.invokeTask @ powerbiportal.dependencies.externals.bundle.min.js:6
h @ powerbiportal.dependencies.externals.bundle.min.js:6
d @ powerbiportal.dependencies.externals.bundle.min.js:6
Show 78 more frames
web.bundle.min.js:6 Set-Cookie header is ignored in response from url: https://app.powerbi.com/tokenRefresh?ver=1559926340769. Cookie length should be less than or equal to 4096 characters.
e.refreshTokenInternal @ web.bundle.min.js:6
e.refreshToken @ web.bundle.min.js:6
P @ powerbiportal.web.bundle.min.js:66
t.invokeTask @ powerbiportal.dependencies.externals.bundle.min.js:6
onInvokeTask @ web.bundle.min.js:6
t.invokeTask @ powerbiportal.dependencies.externals.bundle.min.js:6
r.runTask @ powerbiportal.dependencies.externals.bundle.min.js:6
e.invokeTask @ powerbiportal.dependencies.externals.bundle.min.js:6
i.useG.invoke @ powerbiportal.dependencies.externals.bundle.min.js:6
n @ powerbiportal.dependencies.externals.bundle.min.js:6
setTimeout (async)
i @ powerbiportal.dependencies.externals.bundle.min.js:6
t.scheduleTask @ powerbiportal.dependencies.externals.bundle.min.js:6
onScheduleTask @ powerbiportal.dependencies.externals.bundle.min.js:6
t.scheduleTask @ powerbiportal.dependencies.externals.bundle.min.js:6
r.scheduleTask @ powerbiportal.dependencies.externals.bundle.min.js:6
r.scheduleMacroTask @ powerbiportal.dependencies.externals.bundle.min.js:6
n @ powerbiportal.dependencies.externals.bundle.min.js:6
(anonymous) @ powerbiportal.dependencies.externals.bundle.min.js:6
r.<computed> @ powerbiportal.dependencies.externals.bundle.min.js:6
(anonymous) @ powerbiportal.web.bundle.min.js:66
invoke @ powerbiportal.dependencies.externals.bundle.min.js:54
(anonymous) @ powerbiportal.dependencies.externals.bundle.min.js:56
r @ powerbiportal.dependencies.externals.bundle.min.js:18
gb @ powerbiportal.dependencies.externals.bundle.min.js:56
c @ powerbiportal.dependencies.externals.bundle.min.js:32
Uc @ powerbiportal.dependencies.externals.bundle.min.js:32
a.bootstrap @ powerbiportal.dependencies.externals.bundle.min.js:1017
(anonymous) @ web.bundle.min.js:6
(anonymous) @ web.bundle.min.js:6
t.invoke @ powerbiportal.dependencies.externals.bundle.min.js:6
onInvoke @ web.bundle.min.js:6
t.invoke @ powerbiportal.dependencies.externals.bundle.min.js:6
r.run @ powerbiportal.dependencies.externals.bundle.min.js:6
e.run @ web.bundle.min.js:6
e.bootstrap @ web.bundle.min.js:6
c @ web.bundle.min.js:6
e.ngDoBootstrap @ web.bundle.min.js:6
e._moduleDoBootstrap @ web.bundle.min.js:6
(anonymous) @ web.bundle.min.js:6
t.invoke @ powerbiportal.dependencies.externals.bundle.min.js:6
onInvoke @ web.bundle.min.js:6
t.invoke @ powerbiportal.dependencies.externals.bundle.min.js:6
r.run @ powerbiportal.dependencies.externals.bundle.min.js:6
(anonymous) @ powerbiportal.dependencies.externals.bundle.min.js:7
t.invokeTask @ powerbiportal.dependencies.externals.bundle.min.js:6
onInvokeTask @ web.bundle.min.js:6
t.invokeTask @ powerbiportal.dependencies.externals.bundle.min.js:6
r.runTask @ powerbiportal.dependencies.externals.bundle.min.js:6
o @ powerbiportal.dependencies.externals.bundle.min.js:6
Show 19 more frames

**Comment by qingcheng52** [comment]
> > It's old project. You need to remove "dependencies" to resolve error. It's for R-visuals only. The new tools gives error if you forget to create dependencies.json file.
> > Or you can consider to use another branch:
> > https://github.com/microsoft/powerbi-visuals-gantt/tree/dev/next
> > In this branch the visual converted to use by new tools.
> > You can get blank visual in case on some error in the visual at runtime. Could you share browser console output?
> 
> Hi zBritva,
> Many thanks for the reply! I tried the new branch too, the visual is still blank:(
> I attached the browser console as below, I can see there are some warnings, but I have no clue how to fix them.
> 
> ![image](https://user-images.githubusercontent.com/23001491/59120148-7f011880-8909-11e9-8326-348ce585d9c4.png)

Hi zBritva,
After testing with some other samples, I find the reason. The visual is blank if the apiVersion is 1.13.0, it works fine with other apiVersion like 2.3.0.
I want to update the version using "pbiviz update 2.3.0", but the visual is still blank.
Any idea to make it work?

**Comment by zBritva** [comment]
@qingcheng52 there PR with update API to 2.6.0 and with other new features: 
https://github.com/microsoft/powerbi-visuals-gantt/pull/143

And Gantt visual requires to fill "Start date" with "Duration" or "Start date" with "End date".

**Comment by qingcheng52** [comment]
> @qingcheng52 there PR with update API to 2.6.0 and with other new features:
> [microsoft/powerbi-visuals-gantt#143](https://github.com/microsoft/powerbi-visuals-gantt/pull/143)
> 
> And Gantt visual requires to fill "Start date" with "Duration" or "Start date" with "End date".

Hi zBritva,
Thanks so much for the suggestion. I tried the other branch with api version 2.3.0 and it worked fine in my computer.
https://github.com/microsoft/powerbi-visuals-gantt/tree/UI_improvement
